#!/usr/bin/env python

# put arguments on to the lcd

import serial
import sys

from control import cmd


PORT = '/dev/ttyACM0'


if sys.argv[1] in cmd:
    sys.argv[1] = cmd[sys.argv[1]]

args = ' '.join(sys.argv[1:])

with serial.Serial(PORT, 9600, timeout=1) as ser:
    ser.write(args)
