#!/usr/bin/env python

# put stdin on the display

import serial
import sys

PORT = '/dev/ttyACM0'


try:
    args = ' '.join(sys.argv[1:])
except IndexError:
    args = ''

for line in sys.stdin:
    with serial.Serial(PORT, 9600, timeout=1) as ser:
        ser.write(args)
        ser.write(line)
